いいね機能の追加
sya-ri/t5r pull request #6
Opened 2021-09-13 10:16 UTC by sya-ri

2021-09-14 08:49 UTC, Yumemi-TOnodera requested changes
レビューしました。
トランザクションによる排他処理をしないと、削除または作成指定最中に別な更新処理が入る可能性があり、結果意図しない挙動を生みそうです。（多重作成または作成されない、など）

2021-09-14 08:49 UTC, Yumemi-TOnodera commented on app/Http/Livewire/LikeButton.php
> +            $like->delete();
(must)
- トランザクションが必要です。

2021-09-14 08:49 UTC, Yumemi-TOnodera commented on app/Http/Livewire/LikeButton.php
> +            $this->message->like(Auth::user());
(must)
- トランザクションが必要です。

2021-09-15 01:42 UTC, d2verb commented on tests/Feature/MessageTest.php
> +    public function test_click_button_and_add_like()
(should)
自分の投稿を like できないというテストもほしいですね。

2021-09-15 01:42 UTC, d2verb commented on app/Models/Message.php
> +    }
(imo)
認可関連の処理は Laravel の Policy を使うと別ファイルに切り出せてスッキリしますよ。
現状 canLike しかないですけど、canDelete など他の認可処理が増えてくると Model が膨らんで来そうです。
see: https://readouble.com/laravel/8.x/ja/authorization.html#creating-policies

2021-09-15 06:09 UTC, d2verb approved these changes
1 つだけコメントはありますが
![LGTM](https://image.lgtmoon.dev/20736)

2021-09-15 06:09 UTC, d2verb commented on tests/Feature/MessageTest.php
> +        $livewire->assertSet('icon', '❤️');
(nits)
icon は定数で定義したほうが変更に強いし、コードがわかりやすくなるかと思います。
```suggestion
        $livewire->assertSet('icon', LikeButton::LIKED);
```

2021-09-15 07:56 UTC, yumemi-kaizawa approved these changes

2021-09-15 09:14 UTC, merged