メッセージ投稿機能の追加
sya-ri/t5r pull request #7
Opened 2021-09-14 09:59 UTC by sya-ri

2021-09-15 14:24 UTC, d2verb commented on app/Http/Livewire/CreateMessageForm.php
> +        if ($this->content && strlen($this->content) <= self::MaxLength) {
(imo)
フロントエンドとサーバーサイドでバリデーションルールに不整合があります。

- フロント: `content.length <= MaxLength`
- サーバ: `trim(content).length <= MaxLength`

今のところクリティカルな問題にはならないかと思いますが、コードを読むときに頭の切り替えをしなくて済むので、どちらかに揃えたほうがいいでしょう。

個人的には空白を trim する理由が思いつかないので `content.length <= MaxLength` でいいかなと思いますが、@sya-ri さんはなぜ空白を trim したのでしょう？ 🤔

2021-09-15 14:24 UTC, d2verb commented on resources/views/livewire/create-message-form.blade.php
> +    <button class="border-t border-gray-800 bg-green-300 w-full" wire:click="onSubmit">
(suggest)
バリデーションルールに違反した際はエラーを表示したほうが親切かと思います。
see: https://laravel-livewire.com/docs/2.x/input-validation

2021-09-16 04:52 UTC, sya-ri commented on app/Http/Livewire/CreateMessageForm.php
> +        if ($this->content && strlen($this->content) <= self::MaxLength) {
不整合があるのは確かにわかりにくいかもしれませんね。コメントで説明を書いておくことにします。

前後の空白に意味がなく、メッセージが読みにくくなるだけなので trim しておいた方が使いやすいだろうという考えに基づくものです。

2021-09-16 06:22 UTC, d2verb commented on app/Http/Livewire/CreateMessageForm.php
> +        if ($this->content && strlen($this->content) <= self::MaxLength) {
> 前後の空白に意味がなく、メッセージが読みにくくなるだけなので trim しておいた方が使いやすいだろうという考えに基づくものです。

なるほど、そういう思想があっての実装なら OK です。

2021-09-16 09:09 UTC, sya-ri commented on resources/views/livewire/create-message-form.blade.php
> +    <button class="border-t border-gray-800 bg-green-300 w-full" wire:click="onSubmit">
![image](https://user-images.githubusercontent.com/34268371/133584207-f0439ecc-f821-4a09-83f0-dcfc5c2b3954.png)
- HTML を編集して文字数制限を解除しなければこのエラーが出ることはありませんが、エラーを追加しました。
- 空欄の時はメッセージが送信できないのは明らかなので、エラーは追加しませんでした。

2021-09-16 09:23 UTC, Yumemi-TOnodera requested changes
指摘事項ありです

2021-09-16 09:23 UTC, Yumemi-TOnodera commented on app/Http/Livewire/CreateMessageForm.php
> +            if (strlen($this->content) <= self::MaxLength) {
(must)
- マルチバイトの文字列演算は、`mb_`で始まります。

```suggestion
            if (mb_strlen($this->content) <= self::MaxLength) {
```

2021-09-16 09:23 UTC, Yumemi-TOnodera commented on tests/Feature/MessageTest.php
> +        $content = Str::random(CreateMessageForm::MaxLength + 1);
(IMO)
- 日本語文字列（UTF8）、絵文字（UTF8MB4相当）の文字列長さテストもあったほうがよいかもね。

2021-09-16 09:34 UTC, d2verb approved these changes

2021-09-16 09:50 UTC, sya-ri commented on tests/Feature/MessageTest.php
> +        $content = Str::random(CreateMessageForm::MaxLength + 1);
- 256文字のランダムな英字文字列はメッセージが作成できない

というテストを

- 255文字の 'a', 'あ', '😀' は問題なくメッセージを作成できる
- 256文字の 'a', 'あ', '😀' はメッセージが作成できない

というテストに変更しました。御指摘ありがとうございます。

2021-09-17 02:20 UTC, Yumemi-TOnodera approved these changes
LGTM

2021-09-17 05:27 UTC, yumemi-kaizawa approved these changes

2021-09-17 05:28 UTC, merged